name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: git lfs install

      - name: Add remote using Access Token
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://mozaloom:${{ secrets.HG }}@huggingface.co/spaces/mozaloom/Text-Summarizer-HF

      - name: Debug Remote URL
        run: git remote -v

      - name: Push to Hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://mozaloom:${{ secrets.HG }}@huggingface.co/spaces/mozaloom/Text-Summarizer-HF main
